name: firebasestarter
description: Somnio Software flutter firebase start.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  intl: ^0.17.0
  flutter_bloc: ^7.0.0
  firebase_core: ^1.0.2
  firebase_analytics: ^8.1.0
  firebase_crashlytics: ^2.0.4
  firebase_storage: ^8.0.1
  firebase_messaging: ^10.0.0
  firebase_dynamic_links: ^2.0.7
  cloud_firestore: ^1.0.3
  introduction_screen: ^1.0.9
  package_info: ^0.4.3+4
  flutter_launcher_icons: ^0.9.1
  shared_preferences: ^2.0.6
  image_picker: ^0.7.5+4
  cached_network_image: ^2.5.1
  auto_size_text: ^2.1.0
  string_validator: ^0.1.4
  flutter_local_notifications: ^5.0.0
  flutter_icons: ^1.1.0
  flutter_svg: ^0.22.0
  equatable: ^1.2.6
  repository:
    path: packages/repository
  auth:
    path: packages/auth
  firebase_starter_ui:
    path: packages/firebase_starter_ui

flutter_icons:
  android: true
  ios: true
  image_path: "packages/firebase_starter_ui/assets/images/ic_launcher.jpg"

dev_dependencies:
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  bloc_test: ^8.1.0
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - packages/firebase_starter_ui/assets/images/

flutter_native_splash:
  color: "#42a5f5"
  image: packages/firebase_starter_ui/assets/images/somnio_logo.png
  color_dark: "#042a49"
  image_dark: packages/firebase_starter_ui/assets/images/somnio_logo.png
  web: false
