name: firebasestarter
description: Somnio Software flutter firebase start.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  flutter_bloc: ^6.1.0
  rxdart: ^0.24.1
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_crashlytics: ^0.4.0+1
  firebase_auth: ^0.20.1
  firebase_storage: ^7.0.0
  firebase_messaging: ^8.0.0-dev.15
  cloud_firestore: ^0.16.0+1
  google_sign_in: ^4.5.9
  apple_sign_in: ^0.1.0
  flutter_login_facebook: ^0.5.0
  introduction_screen: ^1.0.9
  package_info: ^0.4.3+4
  flutter_launcher_icons: ^0.8.1
  shared_preferences: ^0.5.12+4
  image_picker: ^0.6.7+22
  flutter_feather_icons: ^1.0.3
  cached_network_image: ^2.5.0
  auto_size_text: ^2.1.0
  string_validator: ^0.1.4
  flutter_local_notifications: ^3.0.1+3
  get_it: ^5.0.6
  firebase_remote_config: ^0.6.0
  flutter_icons: ^1.1.0
  flutter_svg:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.jpg"

dev_dependencies:
  flutter_native_splash: ^0.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_native_splash:
  color: "#42a5f5"
  image: assets/somnio_logo.png
  color_dark: "#042a49"
  image_dark: assets/somnio_logo.png
  web: false
