name: auth
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.0.1
  equatable: ^1.2.6
  google_sign_in: ^4.5.9
  sign_in_with_apple: ^3.0.0
  flutter_facebook_auth: ^3.3.3-no-nullsafety

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
