name: Flutter CI

on: [pull_request]

jobs:
  
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      
      # Get flutter dependencies.
      - name: install dependencies
        run: flutter pub get

      # Check for any formatting issues in the code.
      - name: analyze formatting errors
        run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - name: analize linter errors
        run: flutter analyze .

      # Run widget tests for our flutter project.
      - name: run tests
        run: flutter test --exclude-tags='integration_test'
  